git checkout -b Assignment0
git checkout -b Assignment1
git checkout -b Assignment2
git checkout -b Assignment3
git checkout -b Assignment4
git checkout -b Assignment5
git checkout -b Assignment6
git checkout -b Assignment7
git checkout -b Assignment8
git checkout -b Assignment9
git checkout -b Assignment10
